DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilation_events CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title  VARCHAR(50)           NOT NULL,
    pinned BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(2000)  NOT NULL,
    category_id        BIGINT        NOT NULL,
    confirmed_requests BIGINT       NOT NULL,
    created_on         TIMESTAMP     NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP     NOT NULL,
    initiator_id       BIGINT        NOT NULL,
    location_id        BIGINT        NOT NULL,
    paid               BOOLEAN       NOT NULL,
    participant_limit  BIGINT       NOT NULL,
    published_on      TIMESTAMP,
    request_moderation BOOLEAN       NOT NULL,
    state              VARCHAR(16)   NOT NULL,
    title              VARCHAR(120)   NOT NULL,
    views              BIGINT DEFAULT 0,
    CONSTRAINT category_fk FOREIGN KEY (category_id)
        REFERENCES categories (id),
    CONSTRAINT initiator_fk FOREIGN KEY (initiator_id)
        REFERENCES users (id),
    CONSTRAINT location_fk FOREIGN KEY (location_id)
        REFERENCES locations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id     BIGINT      NOT NULL,
    requester_id BIGINT      NOT NULL,
    status       VARCHAR(16) NOT NULL,
    created      TIMESTAMP   NOT NULL,
    UNIQUE (event_id, requester_id),
    CONSTRAINT requests_event_fk FOREIGN KEY (event_id)
        REFERENCES events (id),
    CONSTRAINT requests_user_fk FOREIGN KEY (requester_id)
        REFERENCES users (id)
);

CREATE TABLE compilation_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT ce_compilation_fk FOREIGN KEY (compilation_id)
        REFERENCES compilations (id),
    CONSTRAINT ce_event_fk FOREIGN KEY (event_id)
        REFERENCES events (id)
);


